repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
  - id: terragrunt-hclfmt
    name: Run terragrunt hclfmt during git commit
    entry: terragrunt hclfmt
    stages: [commit]
